/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingPageIndexRouteImport } from './routes/landing-page/index'

const LandingPageIndexRoute = LandingPageIndexRouteImport.update({
  id: '/landing-page/',
  path: '/landing-page/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/landing-page': typeof LandingPageIndexRoute
}
export interface FileRoutesByTo {
  '/landing-page': typeof LandingPageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/landing-page/': typeof LandingPageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/landing-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/landing-page'
  id: '__root__' | '/landing-page/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingPageIndexRoute: typeof LandingPageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing-page/': {
      id: '/landing-page/'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LandingPageIndexRoute: LandingPageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
